### ISSUE TITLE
Stress test case generator template

### ISSUE THREAD

**Issue by DrSwad** [IEEE-NITK/CodePal#58]
The extension allows defining a pre-written template for solution files (both for general & brute). But there doesn't seem to be any way to define one for test case generation during stress testing. It would be really helpful (at least for me :) ) if this feature could be implemented. I have some pre-written utility functions for generating test cases and it'd be really convenient to be able to include them automatically every time I generate stress testing files, instead of having to find and copy them manually from my template.

**Comment by adityachirania** [comment]
Yeah thats true. What can be done is that a path for the generate template can be taken from the settings and incase its blank, the current template can be rendered by default. Would you like to work on this ?
