### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by lomadapraveenreddy** [IEEE-NITK/CodePal#7]
- [x] Submit Problem Button
- [x] Filters Based on Tags and Ratings
- [ ] Submitting Problem Using selenium web drivers
- [x] Manually adding new test cases

**Comment by adityachirania** [comment]
Using selenium web drivers doesnt seem possible for now. Remaining 3 features have been successfully added.

**Comment by Siddhant-K-code** [comment]
can't we just upload the file to the solution?

**Comment by adityachirania** [comment]
Do you mean upload automatically ?
In that case we ll need to store cookies of the user so that we can automatically upload code for him .
