### ISSUE TITLE
Feature request: Addition of problems using their webpage link

### ISSUE THREAD

**Issue by priyanshul-govil** [IEEE-NITK/CodePal#81]
It would be nice to be able to add problems using their webpage link. This would allow for automatic fetching of the test cases.

**Comment by adityachirania** [comment]
Which exact problems are you talking about ? are you referring to problems on codeforces ?

**Comment by priyanshul-govil** [comment]
@adityachirania Yes, codeforces problems. Right now, the only way creating a folder fetches the test cases is if you select a contest/problem from the viewable list.

I was suggesting adding problems externally, say for example using a link like https://codeforces.com/contest/1549/problem/C, and the test cases could be autofetched from here.

**Comment by adityachirania** [comment]
Okay so vs code has this feature where if you start typing the problem name after clicking on any row in the tree view, It would show all matching results and you would have found the problem/contest you need this way. I'll still add this as one of the possible things that we could add for our next release.

**Comment by priyanshul-govil** [comment]
Oh, cool. I didn't know about this.
