### ISSUE TITLE
The form of the input.txt file is always wrong

### ISSUE THREAD

**Issue by glotm** [IEEE-NITK/CodePal#97]
![image](https://user-images.githubusercontent.com/69087402/185638698-d363fa9c-55b0-4f33-acd8-4c67344a8a7c.png)
I do nothing but this file always like this.

**Comment by Dragonado** [comment]
Hi, I think this happened because CodeForces introduced test case highlighting feature. We patched it several weeks ago. Are you still facing this issue? If not, I will close this issue.
